### ISSUE TITLE
Most of commands dont work

### ISSUE THREAD

**Issue by callmelasagna** [diwasatreya/Music-Bot-v2#3]
- Console : `ReferenceError: message is not defined
    at Object.run (/home/runner/Music-Bot-v2/SlashCommands/MUSIC/join.js:13:14)
    at module.exports.run (/home/runner/Music-Bot-v2/events/interactionCreate.js:44:21)
    at Client.emit (node:events:527:28)
    at InteractionCreateAction.handle (/home/runner/Music-Bot-v2/node_modules/discord.js/src/client/actions/InteractionCreate.js:83:12)
    at Object.module.exports [as INTERACTION_CREATE] (/home/runner/Music-Bot-v2/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/runner/Music-Bot-v2/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/home/runner/Music-Bot-v2/node_modules/discord.js/src/client/websocket/WebSocketShard.js:478:22)
    at WebSocketShard.onMessage (/home/runner/Music-Bot-v2/node_modules/discord.js/src/client/websocket/WebSocketShard.js:317:10)
    at WebSocket.onMessage (/home/runner/Music-Bot-v2/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:527:28)`
 
 - SS : [here](https://media.discordapp.net/attachments/1027573967948623872/1027576917823606865/unknown.png?width=720&height=500)

**Comment by RXNationGMG** [comment]
Same Here :(

**Comment by RXNationGMG** [comment]
@diwasatreya Please Fix Your Commands, It Is Not Working
